### PR TITLE
Fix report issue button

### LINKED ISSUE #249: Report Issue Button UI Mismatch
Figma Design:

Image

Current:

Image

### PR DESCRIPTION
**Pull request by caleb-bit**
## Overview
This PR fixes the report issue icon and the button shape.

## Related PRs or Issues
- Resolves #249 

## Summary by CodeRabbit

* **Style**
  * Standardized "Report an issue" button appearance and icon across detail and support screens for a consistent look and feel.
* **New Features**
  * Introduced a unified report button component used throughout the app, preserving the tap action to open the report sheet.
* **Bug Fixes**
  * FAQ and menu actions now reliably close menus before invoking actions, improving interaction behavior.

### CODE REVIEW

File: app/src/main/java/com/cornellappdev/android/eatery/ui/screens/SupportScreen.kt [hunk 1]
```diff
@@ -264,8 +270,8 @@ private fun SupportScreenContent(
         FAQCreation(
             title = stringResource(R.string.support_faq_order_title),
             dropdownText = stringResource(id = R.string.order_on_eatery),
-            action = {
-                Row {
+            action = { onClick ->
+                Row(modifier = Modifier.clickable { onClick() }) {
```
Comment (AndrewCheung360) [inline app/src/main/java/com/cornellappdev/android/eatery/ui/screens/SupportScreen.kt]: Nit: was probably there before, but we can use TextButton instead of clickable rows

**Review by AndrewCheung360 — APPROVED** [review]
LGTM. minor comment about TextButton from code that was there before.
